# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.10
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 55320885+Pasquale-Silv@users.noreply.github.com
author_name: Pasquale.Silv
contract_name: voting_sc
deployment_language: python
preset_name: production
project_name: voting-contracts

